switch to direct gitea mirror

diff --git a/sources/apps-aur/apps-aur.install b/sources/apps-aur/apps-aur.install
--- a/sources/apps-aur/apps-aur.install
+++ b/sources/apps-aur/apps-aur.install
@@ -1,4 +1,5 @@
 closeHook() {
+    mv -vf /var/lib/pacman/db.lck.unlock /var/lib/pacman/db.lck
     sed -i '$ d' /etc/sudoers # remove last entry
     echo "remove NOPASSWD from /etc/sudoers"
 }
@@ -8,14 +9,24 @@ install_aur_packages() {
     [ -z "$user" ] && return
     echo "add NOPASSWD to /etc/sudoers"
     echo "$user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
-    trap closeHook SIGHUP SIGINT SIGTERM EXIT
     mv -vf /var/lib/pacman/db.lck /var/lib/pacman/db.lck.unlock
-    # su $user -c 'yay --noconfirm --needed -S backintime' # Simple backup system. QT5 GUI version
-    su $user -c 'yay --noconfirm --needed -S brave-bin' # Web browser that blocks ads and trackers by default
-    # su $user -c 'yay --noconfirm --needed -S slack-desktop' # Slack Desktop (Beta) for Linux
-    su $user -c 'yay --noconfirm --needed -S spotify-adblock-git' # Adblocker for Spotify
-    su $user -c 'yay --noconfirm --needed -S visual-studio-code-bin' # Visual Studio Code Editor
-    mv -vf /var/lib/pacman/db.lck.unlock /var/lib/pacman/db.lck
+    trap closeHook SIGHUP SIGINT SIGTERM EXIT
+    AUR_HELPER=""
+    if command -v yay >/dev/null ; then
+        AUR_HELPER="yay"
+    elif command -v paru >/dev/null ; then
+        AUR_HELPER="paru"
+    fi
+    if [ -z "$AUR_HELPER" ]; then
+        echo "ERROR: No AUR helper found!"
+        exit 1
+    else
+        su $user -c "$AUR_HELPER --noconfirm --needed -S rbw-git" # unofficial bitwarden cli
+        su $user -c "$AUR_HELPER --noconfirm --needed -S brave-bin" # Web browser that blocks ads and trackers by default
+        # su $user -c "$AUR_HELPER --noconfirm --needed -S slack-desktop" # Slack Desktop (Beta) for Linux
+        su $user -c "$AUR_HELPER --noconfirm --needed -S spotify-adblock-git" # Adblocker for Spotify
+        su $user -c "$AUR_HELPER --noconfirm --needed -S visual-studio-code-bin" # Visual Studio Code Editor
+    fi
 }
 
 pre_install() {
diff --git a/sources/base-wm-aur/base-wm-aur.install b/sources/base-wm-aur/base-wm-aur.install
--- a/sources/base-wm-aur/base-wm-aur.install
+++ b/sources/base-wm-aur/base-wm-aur.install
@@ -1,4 +1,5 @@
 closeHook() {
+    mv -vf /var/lib/pacman/db.lck.unlock /var/lib/pacman/db.lck
     sed -i '$ d' /etc/sudoers # remove last entry
     echo "remove NOPASSWD from /etc/sudoers"
 }
@@ -8,14 +9,23 @@ install_aur_packages() {
     [ -z "$user" ] && return
     echo "add NOPASSWD to /etc/sudoers"
     echo "$user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
-    trap closeHook SIGHUP SIGINT SIGTERM EXIT
     mv -vf /var/lib/pacman/db.lck /var/lib/pacman/db.lck.unlock
-    # su $user -c 'yay --noconfirm --needed -S bitwarden-cli' # dmenu adapter for bitwarden-cli
-    su $user -c 'yay --noconfirm --needed -S genact' # A nonsense activity generator
-    su $user -c 'yay --noconfirm --needed -S j4-dmenu-desktop' # A much faster replacement for i3-dmenu-desktop
-    su $user -c 'yay --noconfirm --needed -S lazygit' # A simple terminal UI for git commands
-    su $user -c 'yay --noconfirm --needed -S lf' # A terminal file manager inspred by ranger written in Go
-    mv -vf /var/lib/pacman/db.lck.unlock /var/lib/pacman/db.lck
+    trap closeHook SIGHUP SIGINT SIGTERM EXIT
+    AUR_HELPER=""
+    if command -v yay >/dev/null ; then
+        AUR_HELPER="yay"
+    elif command -v paru >/dev/null ; then
+        AUR_HELPER="paru"
+    fi
+    if [ -z "$AUR_HELPER" ]; then
+        echo "ERROR: No AUR helper found!"
+        exit 1
+    else
+        su $user -c "$AUR_HELPER --noconfirm --needed -S genact" # A nonsense activity generator
+        su $user -c "$AUR_HELPER --noconfirm --needed -S j4-dmenu-desktop" # A much faster replacement for i3-dmenu-desktop
+        su $user -c "$AUR_HELPER --noconfirm --needed -S lazygit" # A simple terminal UI for git commands
+        su $user -c "$AUR_HELPER --noconfirm --needed -S lf" # A terminal file manager inspred by ranger written in Go
+    fi
 }
 
 pre_install() {
diff --git a/sources/login-greetd-aur/login-greetd-aur.install b/sources/login-greetd-aur/login-greetd-aur.install
--- a/sources/login-greetd-aur/login-greetd-aur.install
+++ b/sources/login-greetd-aur/login-greetd-aur.install
@@ -1,4 +1,5 @@
 closeHook() {
+    mv -vf /var/lib/pacman/db.lck.unlock /var/lib/pacman/db.lck
     sed -i '$ d' /etc/sudoers # remove last entry
     echo "remove NOPASSWD from /etc/sudoers"
 }
@@ -8,16 +9,26 @@ install_aur_packages() {
     [ -z "$user" ] && return
     echo "add NOPASSWD to /etc/sudoers"
     echo "$user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
-    trap closeHook SIGHUP SIGINT SIGTERM EXIT
     mv -vf /var/lib/pacman/db.lck /var/lib/pacman/db.lck.unlock
-    su $user -c 'yay --noconfirm --needed -S greetd' # Generic greeter daemon
+    trap closeHook SIGHUP SIGINT SIGTERM EXIT
+    AUR_HELPER=""
+    if command -v yay >/dev/null ; then
+        AUR_HELPER="yay"
+    elif command -v paru >/dev/null ; then
+        AUR_HELPER="paru"
+    fi
+    if [ -z "$AUR_HELPER" ]; then
+        echo "ERROR: No AUR helper found!"
+        exit 1
+    else
+        su $user -c "$AUR_HELPER --noconfirm --needed -S greetd" # Generic greeter daemon
 
-    sed -i 's/^user = .*/user = "'$user'"/g' /etc/greetd/config.toml
-    sed -i 's/^command = .*/command = "tuigreet --cmd startx"/g' /etc/greetd/config.toml
+        sed -i 's/^user = .*/user = "'$user'"/g' /etc/greetd/config.toml
+        sed -i 's/^command = .*/command = "tuigreet --cmd startx"/g' /etc/greetd/config.toml
 
-    # Install after config.toml changes!
-    su $user -c 'yay --noconfirm --needed -S tuigreet' # A console UI greeter for greetd
-    mv -vf /var/lib/pacman/db.lck.unlock /var/lib/pacman/db.lck
+        # Install after config.toml changes!
+        su $user -c "$AUR_HELPER --noconfirm --needed -S tuigreet" # A console UI greeter for greetd
+    fi
 }
 
 pre_install() {
diff --git a/sources/xorg-wm-aur/xorg-wm-aur.install b/sources/xorg-wm-aur/xorg-wm-aur.install
--- a/sources/xorg-wm-aur/xorg-wm-aur.install
+++ b/sources/xorg-wm-aur/xorg-wm-aur.install
@@ -1,4 +1,5 @@
 closeHook() {
+    mv -vf /var/lib/pacman/db.lck.unlock /var/lib/pacman/db.lck
     sed -i '$ d' /etc/sudoers # remove last entry
     echo "remove NOPASSWD from /etc/sudoers"
 }
@@ -8,15 +9,25 @@ install_aur_packages() {
     [ -z "$user" ] && return
     echo "add NOPASSWD to /etc/sudoers"
     echo "$user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
-    trap closeHook SIGHUP SIGINT SIGTERM EXIT
     mv -vf /var/lib/pacman/db.lck /var/lib/pacman/db.lck.unlock
-    su $user -c 'yay --noconfirm --needed -S dragon-drag-and-drop' # Simple drag-and-drop source/sink for X
-    su $user -c 'yay --noconfirm --needed -S i3lock-color' # Improved screenlocker with color configuration support
-    su $user -c 'yay --noconfirm --needed -S picom-jonaburg-git' # picom fork with dual_kawase blur and rounded corners
-    su $user -c 'yay --noconfirm --needed -S xcolor' # display and grab colors in X
-    su $user -c 'yay --noconfirm --needed -S xidlehook' # xautolock rewrite in Rust, with a few extra features
-    su $user -c 'yay --noconfirm --needed -S xob' # A lightweight volume (or anything) bar for the X Window System"
-    mv -vf /var/lib/pacman/db.lck.unlock /var/lib/pacman/db.lck
+    trap closeHook SIGHUP SIGINT SIGTERM EXIT
+    AUR_HELPER=""
+    if command -v yay >/dev/null ; then
+        AUR_HELPER="yay"
+    elif command -v paru >/dev/null ; then
+        AUR_HELPER="paru"
+    fi
+    if [ -z "$AUR_HELPER" ]; then
+        echo "ERROR: No AUR helper found!"
+        exit 1
+    else
+        su $user -c "$AUR_HELPER --noconfirm --needed -S dragon-drag-and-drop" # Simple drag-and-drop source/sink for X
+        su $user -c "$AUR_HELPER --noconfirm --needed -S i3lock-color" # Improved screenlocker with color configuration support
+        su $user -c "$AUR_HELPER --noconfirm --needed -S picom-jonaburg-git" # picom fork with dual_kawase blur and rounded corners
+        su $user -c "$AUR_HELPER --noconfirm --needed -S xcolor" # display and grab colors in X
+        su $user -c "$AUR_HELPER --noconfirm --needed -S xidlehook" # xautolock rewrite in Rust, with a few extra features
+        su $user -c "$AUR_HELPER --noconfirm --needed -S xob" # A lightweight volume (or anything) bar for the X Window System"
+    fi
 }
 
 pre_install() {
